### ISSUE TITLE
Truss and beam elements disconnected

### ISSUE THREAD

**Issue by victorkemp** [Dhondtguido/CalculiX#14]
They should both deflect at their common node but the truss behaves like it isn't connected to the beam.

```
*NODE
1,0,0,0
2,0,0.625,0
3,0,0.875,0
4,0,0.5,0
5,0,0.125,0
6,0,0.75,0
7,0,0.375,0
8,0,1,0
9,0,1.125,0
10,0,0.25,0
11,-0.5,0.5,0
*ELEMENT,TYPE=B31,ELSET=1
1,5,1
2,10,5
3,9,8
4,8,3
5,3,6
6,6,2
8,7,10
9,2,4
10,4,7
*ELEMENT,TYPE=T3D2,ELSET=2
7,11,4
*MATERIAL,NAME=Material
*ELASTIC,TYPE=ISOTROPIC
200000000000,0
*BEAM SECTION,ELSET=1,MATERIAL=Material,SECTION=RECT
0.05,0.05
1,0,0
*SOLID SECTION,ELSET=2,MATERIAL=Material
0.0025
*BOUNDARY
1,1,3,0
9,1,3,0
11,1,3,0
*STEP
*STATIC
*CLOAD
2,3,1000
*NODE FILE
U
*END STEP
```
![Untitled](https://user-images.githubusercontent.com/118495694/203892472-4d78715b-ca62-4180-a7cb-91eb4ee34397.png)

**Comment by FEA-eng** [comment]
It seems that this issue is fixed in CalculiX 2.21.

**Comment by victorkemp** [comment]
It's not really fixed. In 2.21, they're not disconnected anymore but instead are connected too hard. The beams don't deflect as far as without the truss, which should have no impact on the solution. I think it's just a coincidence and it still needs a proper fix which is moving `beam=.false.` outside the loop in gen3dnor.f starting around line 455.

**Comment by stefano2734** [comment]
Also in actual version  2.23?

**Comment by Durbul** [comment]
Fixed in https://github.com/Dhondtguido/CalculiX/commit/fd1eb023cd4418fa6197a73f2edd2b6cff9df374
